version: "3.8"

services:

  db:
    image: mysql
    container_name: mysql-soroteca
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    expose: 
    - 3306
    ports:
      - 3306:3306
  api:
    build:
         "./BackEnd"
    container_name: node_container      
    restart: always
    volumes:
      - /Soroteca/BackEnd/
    ports:
      - 8888:8888
    depends_on:
      - db